name: "Clasp Action"
description: "Push or deploy to Google Apps Script using clasp"
branding:
  icon: "arrow-up-circle"
  color: "blue"
inputs:
  clasprcJson:
    description: "Full .clasprc.json file"
    required: true
  scriptId:
    description: "scriptId written in .clasp.json"
    required: true
  rootDir:
    description: "Directory where scripts are stored"
    required: false
  command:
    description: "Command to execute(push or deploy)"
    required: true
  description:
    description: "Description of the deployment"
    required: false
  deployId:
    description: "Deploy ID that will be updated"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.accessToken }}
    - ${{ inputs.scriptId }}
    - ${{ inputs.rootDir }}
    - ${{ inputs.command }}
    - ${{ inputs.description }}
    - ${{ inputs.deployId }}
